apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - replica-patch.yaml
images:
  - name: stock-sim/trading-service
    newTag: "1.0.0"
  - name: stock-sim/user-service
    newTag: "1.0.0"
